spring:
  datasource:
#    url: jdbc:postgresql://123.60.47.141:5432/xmap_v2
#    username: postgres
#    password: Cvrs213#@!
    url: jdbc:postgresql://123.60.47.141:5432/xmap
    username: postgres
    password: Cvrs213#@!
#  cache:
#    jcache:
#      config: classpath:ehcache.xml
  redis:
    host: 127.0.0.1       #Redis 地址
    port: 6379            #Redis 端口号
    database: 1           #Redis 索引（0~15，默认为0）
    timeout: 1000         #Redis 连接的超时时间
    lettuce: #使用 lettuce 连接池
      pool:
        max-active: 20    #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0       #连接池中的最大空闲连接
        max-idle: 10      #连接池中的最小空闲连接
  cache:
    type: redis
    cache-names: redisCache
    redis:
      cache-null-values: true
      use-key-prefix: true
      time-to-live: 0

mybatis-plus:
  configuration:
    cache-enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true

Minio:
  url: http://123.60.47.141:9000
  accessKey: minioadmin
  secretKey: cvrs213minio#@!